### ISSUE TITLE
IndexedDB not working

### ISSUE THREAD

**Issue by ecerroni** [lcavadas/Storage.js#3]
It works with any type but IndexedDB. For instance it doesn't store anything locally.

I'm using:
- OS: Ubuntu Gnome
- Google Chrome: Version 49.0.2623.87 (64-bit).

**Comment by lcavadas** [comment]
It's a bit late over here, I'll take a look tomorrow to fix it.

**Comment by ecerroni** [comment]
May be I've jumped too quickly to conclusions. I've checked the indexedDB availability writing in my Chrome console with the following code:

var idbSupported = false;
 
document.addEventListener("DOMContentLoaded", function(){
 
    if("indexedDB" in window) {
        idbSupported = true;
    }
 
},false);

I attach the screenshot.

And the result is false. It seems it's not supported by my browser event though it should. That's why it's not working when I forcing through storage(readyCallback ,'IndexedDB')
